openapi: 3.0.0
info:
  version: '1.0'
  title: 'Quantop'
  description: 'APIs for quantop'

servers:
# Added by API Auto Mocking Plugin
  - description: Quantop API
    url: http://localhost:3000/quantop/1.0

paths:
  /users/{userId}:
    get:
      summary: Returns a user by ID
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        '400':
          description: The specified user ID is invalid (e.g. not a number)
        '404':
          description: A user with the specified ID was not found